### ISSUE TITLE
发行资产功能bug反馈

### ISSUE THREAD

**Issue by wxt7325716** [sqfasd/asch#4]
[bug反馈.docx](https://github.com/sqfasd/asch/files/768175/bug.docx)

**Comment by sqfasd** [comment]
每个问题建立一个issue就行了，最好直接把问题描述贴出来，不要上传文件，只有文件比较大的时候，比如log文件才需要上传

**Comment by sqfasd** [comment]
1. 第一个问题，你实际转账的时候输入的50000与你设置的最大值6000不是一个单位，它们之间的差距就是你设置的精确度, 数据库实际存的数值是amount * 10^precision, 比如，最大值是6000，数据库中存的是60000，所以当你转账50000的时候，并没有超过限额。
这是前端展示的问题，前端输入的数据统一处理就行了
2. 密码没有隐藏的问题已修复
3. 已注销的是资产依然可以查到，只是做了注销标记

**Comment by sqfasd** [comment]
第一个问题，我刚才表达有误，我又查看了下交易数据，和代码对比了下，你输入的应该是5000，只是你查看操作记录的时候，展示的是50000，这个是没问题的，只是展示的单位不一样。
比方说，你实际上花了5块钱，但是后台记录你花费了500分，就是这个意思

**Comment by wxt7325716** [comment]
好的，不过能否标注下单位，避免产生歧义，另外，A转移发行数字资产给B，B只有在首页-》我的交易看到流水，且流水后面金额显示为0(只有在转移阿希币才有值)，这样B其实不方便进行统计，能否在首页-》我的交易-》金额 也显示发行资产的金额
